#sdk: "C:/RhoMobileSuite5.3.2/ruby/lib/ruby/gems/1.9.1/gems/rhodes-5.3.2"
sdkversion: "5.3.2"
name: "rhomobile"
version: 1.0
vendor: "rhomobile"
build: "debug"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator8.2"
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: 
  BundleIdentifier: "com.rhomobile.rhomobile"
  BundleURLScheme: "rhomobile"
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
wp8:
  productid: "c2542400-a98e-0133-e763-0000da327cd9"
android:
#manifest_template: 'AndroidManifest.erb'
  version: "4.1.0"
# Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: "APP:I StrictMode:I DEBUG:I *:E"
  emulator: "API19"
wm: 
#sdk: "MC3000c50b (ARMV4I)"
#sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
win32:
  deployqt: 1
  deploymsvc: 1
extensions:
  - rhoconnect-client
rhobundle:
  exclude_items:
    - thumb.db
