<?php
//Nom de l'appli
define("_NOM_APPLI", "Rennes en Poche");

//Catégories
define("_ALIMENTAIRE", "Alimentaire");
define("_VETEMENT", "Vêtements");
define("_TECHNOLOGIE", "Technologie");
define("_CULTUREL", "Culturel");
define("_MOBILIER", "Mobilier");
define("_SERVICES", "Services");
define("_LOGEMENT", "Logement");
define("_MEDICAL", "Médical");
define("_VIE_NOCTURNE", "Vie nocturne");
define("_CATEGORIES", "Catégories");

//Bouton bas de page
define("_PROFILE", "Mon Profil");
define("_ACCUEIL", "Accueil");
define("_RETOUR", "Retour");

//Bouton Page d'accueil
define("_CREER_PARCOURS", "Créer son propre parcours");

//Page votre parcours
define("_VOTRE_PARCOURS", "Votre Parcours");
define("_GENERER_PARCOURS", "Générer le parcours");

//Type de magasins (sous-catégories)
?>